#!/usr/bin/env bash
# Apply updates to a remote Mac over SSH based on APPLY: lines in a report file.
# Usage: apply-updates.sh <report-file> <ssh-alias> [flags]
#
# Flags (all opt-in for safety):
#   --dry-run        Print the remote script that would run, do not execute.
#   --new-formulae   Install formulae present on baseline but missing on target.
#   --new-casks      Install casks present on baseline but missing on target.
#   --new-mas        Install MAS apps present on baseline but missing on target.
#   --macos          Apply macOS minor (security) updates (requires restart on target).
#   --no-vscode      Skip VS Code extension installs.
#   --no-git         Skip dotty/oh-my-zsh git pulls.
#   --no-blueprint   Skip system-blueprint apply lane.
#   --blueprint-prune  Apply blueprint slices in --prune mode (full reconcile).
#
# Default-applied lanes: brew_upgrade_*, mas_upgrade, vscode_install_ext,
#   git_pull*, blueprint apply (additive).
#   These are low-risk and reversible — they only update things already installed
#   (blueprint apply default is additive, never removes undeclared items).
# Opt-in lanes (require explicit flag — human decides relevance):
#   brew_install_formula, brew_install_cask, mas_install, macos_minor,
#   blueprint --prune.

set -uo pipefail

REPORT="${1:?report file from diff-state.sh}"
HOST="${2:?ssh alias of target host}"
shift 2

DRY=0
NEW_CASKS=0
NEW_MAS=0
NEW_FORMULAE=0
INCLUDE_MACOS=0
DO_VSCODE=1
DO_GIT=1
DO_BLUEPRINT=1
BLUEPRINT_PRUNE=0

while [ $# -gt 0 ]; do
  case "$1" in
    --dry-run)         DRY=1 ;;
    --new-formulae)    NEW_FORMULAE=1 ;;
    --new-casks)       NEW_CASKS=1 ;;
    --new-mas)         NEW_MAS=1 ;;
    --macos)           INCLUDE_MACOS=1 ;;
    --no-vscode)       DO_VSCODE=0 ;;
    --no-git)          DO_GIT=0 ;;
    --no-blueprint)    DO_BLUEPRINT=0 ;;
    --blueprint-prune) BLUEPRINT_PRUNE=1 ;;
    *) echo "unknown flag: $1" >&2; exit 2 ;;
  esac
  shift
done

[ -f "$REPORT" ] || { echo "missing report: $REPORT" >&2; exit 1; }

# Read APPLY: lines and categorize.
applies=$(grep '^APPLY:' "$REPORT" || true)

formulae_upgrade=$(printf '%s\n' "$applies" | sed -nE 's/^APPLY: brew_upgrade_formula name=(.*)/\1/p')
casks_upgrade=$(   printf '%s\n' "$applies" | sed -nE 's/^APPLY: brew_upgrade_cask name=(.*)/\1/p')
mas_upgrade=$(     printf '%s\n' "$applies" | sed -nE 's/^APPLY: mas_upgrade id=(.*)/\1/p')
formulae_install=$(printf '%s\n' "$applies" | sed -nE 's/^APPLY: brew_install_formula name=(.*)/\1/p')
casks_install=$(   printf '%s\n' "$applies" | sed -nE 's/^APPLY: brew_install_cask name=(.*)/\1/p')
mas_install_ids=$( printf '%s\n' "$applies" | sed -nE 's/^APPLY: mas_install id=(.*)/\1/p')
vscode_exts=$(     printf '%s\n' "$applies" | sed -nE 's/^APPLY: vscode_install_ext id=(.*)/\1/p')
git_pull_repos=$(  printf '%s\n' "$applies" | sed -nE 's/^APPLY: git_pull repo=(.*)/\1/p')
git_pull_paths=$(  printf '%s\n' "$applies" | sed -nE 's/^APPLY: git_pull_path path=(.*)/\1/p')
macos_labels=$(    printf '%s\n' "$applies" | sed -nE 's/^APPLY: macos_minor label="?([^"]*)"?$/\1/p' \
                   | grep -Ev '^Safari[0-9]' || true)  # never auto-apply Safari major bumps

# Build remote script.
remote=$(mktemp /tmp/update-mbp-remote.XXXXXX.sh)
trap 'rm -f "$remote"' EXIT

{
  cat <<'HEAD'
#!/usr/bin/env bash
# Generated by update-mbp/apply-updates.sh — do not edit; will be overwritten.
set -uo pipefail
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/local/sbin:$PATH"

step() { printf '\n──── %s ────\n' "$*"; }
HEAD

  echo
  # Use single quotes so the command substitutions expand on the *remote* host
  # at run time, not on the Mini at generation time.
  # shellcheck disable=SC2016  # intentional: no expansion here, expands remotely
  echo 'step "host: $(hostname) os: $(sw_vers -productVersion 2>/dev/null)"'
  echo "step 'updating Homebrew metadata'"
  echo "brew update || true"

  if [ -n "$formulae_upgrade$casks_upgrade" ]; then
    echo "step 'upgrading existing Homebrew packages'"
    if [ -n "$formulae_upgrade" ]; then
      printf 'brew upgrade --formula %s || true\n' "$(echo "$formulae_upgrade" | tr '\n' ' ')"
    fi
    if [ -n "$casks_upgrade" ]; then
      printf 'brew upgrade --cask %s || true\n' "$(echo "$casks_upgrade" | tr '\n' ' ')"
    fi
  fi

  if [ "$NEW_FORMULAE" = "1" ] && [ -n "$formulae_install" ]; then
    echo "step 'installing formulae present on baseline but missing here'"
    printf 'brew install %s || true\n' "$(echo "$formulae_install" | tr '\n' ' ')"
  fi

  if [ "$NEW_CASKS" = "1" ] && [ -n "$casks_install" ]; then
    echo "step 'installing casks present on baseline but missing here'"
    for c in $casks_install; do
      echo "brew install --cask $c || true"
    done
  fi

  if [ -n "$mas_upgrade" ]; then
    echo "step 'upgrading Mac App Store apps'"
    echo "if command -v mas >/dev/null 2>&1; then"
    for id in $mas_upgrade; do
      echo "  mas upgrade $id || true"
    done
    echo "else echo 'mas not installed; skipped'; fi"
  fi

  if [ "$NEW_MAS" = "1" ] && [ -n "$mas_install_ids" ]; then
    echo "step 'installing missing Mac App Store apps'"
    echo "if command -v mas >/dev/null 2>&1; then"
    for id in $mas_install_ids; do
      echo "  mas install $id || true"
    done
    echo "else echo 'mas not installed; skipped'; fi"
  fi

  if [ "$DO_VSCODE" = "1" ] && [ -n "$vscode_exts" ]; then
    echo "step 'installing VS Code extensions'"
    echo "if command -v code >/dev/null 2>&1; then"
    for ext in $vscode_exts; do
      echo "  code --install-extension $ext --force || true"
    done
    echo "else echo 'code CLI not installed; skipped'; fi"
  fi

  if [ "$DO_GIT" = "1" ] && [ -n "$git_pull_repos$git_pull_paths" ]; then
    echo "step 'pulling tracked git repos'"
    # Build a deduped list of $HOME-relative paths.
    pull_paths=$(
      {
        for repo in $git_pull_repos; do echo "bin/$repo"; done
        for path in $git_pull_paths; do echo "$path"; done
      } | awk 'NF && !seen[$0]++'
    )
    # Emit a helper function. For repos with an SSH GitHub origin we can't
    # auth via 1Password's agent over a non-TTY SSH session (OpenSSH 10's
    # bind-hostkey requirement vs 1P's missing extension support — see
    # SKILL.md). Workaround scoped to *this skill only*: for that one fetch,
    # use HTTPS and supply the credential helper inline (`-c credential.helper`
    # overrides). The MBP's persistent git config is untouched, so the user's
    # interactive workflow on the MBP (push/pull from a real session, where
    # 1P is alive) keeps using SSH + 1P exactly as before.
    # Prerequisite: `gh auth login` has been run once on the MBP.
    cat <<'PULL_FN'
_ump_pull() {
  local rel="$1"
  local dir="$HOME/$rel"
  [ -d "$dir/.git" ] || { echo "  ⚠ not a git repo: $rel"; return 1; }
  local origin branch url
  origin=$(git -C "$dir" remote get-url origin 2>/dev/null) || { echo "  ⚠ no origin: $rel"; return 1; }
  branch=$(git -C "$dir" rev-parse --abbrev-ref HEAD 2>/dev/null) || { echo "  ⚠ no branch: $rel"; return 1; }
  case "$origin" in
    git@github.com:*)
      url="https://github.com/${origin#git@github.com:}"
      # Scoped credential override: clear inherited helpers, then route to gh
      # for *this invocation only*. Nothing is written to ~/.gitconfig.
      if git -c credential.helper= \
             -c credential.helper='!gh auth git-credential' \
             -C "$dir" fetch --quiet "$url" "$branch" \
         && git -C "$dir" merge --ff-only --quiet FETCH_HEAD; then
        echo "  pulled $rel (via https — gh credential, scoped)"
      else
        echo "  ⚠ pull failed: $rel — is 'gh auth login' done on this machine?"
      fi
      ;;
    *)
      if git -C "$dir" pull --ff-only --quiet; then
        echo "  pulled $rel"
      else
        echo "  ⚠ pull failed: $rel"
      fi
      ;;
  esac
}
PULL_FN
    while IFS= read -r path; do
      [ -n "$path" ] && printf '_ump_pull %q\n' "$path"
    done <<< "$pull_paths"
  fi

  # Pre-commit hook activation: runs after git pulls so repos have the latest
  # .pre-commit-config.yaml. Conditional on pre-commit being installed (it would
  # arrive via the Homebrew upgrade/install lane above; if missing, this skips).
  echo "step 'activating pre-commit hooks in repos'"
  cat <<'PRECOMMIT_FN'
if command -v pre-commit >/dev/null 2>&1; then
  for repo_dir in ~/bin/dotty ~/bin/dotty-private; do
    if [ -f "$repo_dir/.pre-commit-config.yaml" ]; then
      (cd "$repo_dir" && pre-commit install 2>/dev/null && echo "  ✓ $(basename $repo_dir)") || echo "  ⚠ failed: $(basename $repo_dir)"
    fi
  done
else
  echo "  pre-commit not installed; skipped (install via: brew install pre-commit)"
fi
PRECOMMIT_FN

  # Gitleaks operator rules: NOT this script's concern. Rules load from the
  # fixed install path (gl_preflight, git-hooks/gitleaks-common.sh) — the
  # system blueprint's gitleaks-rules slice (`apply`, below) installs/updates
  # it. There is no per-repo symlink to create.

  # Capture One user Styles symlink: the .costyle masters live in dotty-private
  # (capture-one/Styles) so they version with the rest of the config and stay
  # available offline while traveling. Links the target's Styles folder to the
  # pulled master. Runs AFTER git pulls so the master exists; idempotent and
  # guarded so it never clobbers a non-empty real Styles folder.
  echo "step 'linking Capture One Styles'"
  cat <<'C1STYLES_FN'
C1_MASTER="$HOME/bin/dotty-private/capture-one/Styles"
C1_TARGET="$HOME/Library/Application Support/Capture One/Styles"
if [ -d "$C1_MASTER" ]; then
  if [ -L "$C1_TARGET" ]; then
    echo "  Styles: already linked"
  elif [ -e "$C1_TARGET" ] && [ -n "$(ls -A "$C1_TARGET" 2>/dev/null)" ]; then
    echo "  ⚠ Styles: non-empty real folder at target — not overwriting; resolve manually"
  else
    rmdir "$C1_TARGET" 2>/dev/null || true
    mkdir -p "$(dirname "$C1_TARGET")"
    ln -s "$C1_MASTER" "$C1_TARGET" && echo "  Styles: linked"
  fi
else
  echo "  C1 styles master not found; skipped (pull dotty-private first)"
fi
C1STYLES_FN

  # System blueprint apply: reproduces harness state (MCP servers, hooks, etc.)
  # from declared state in dotty-private/.claude/blueprint/. Runs AFTER git pulls
  # so we apply the latest blueprint, BEFORE macOS restart so failures surface.
  # Default is additive (non-destructive); --blueprint-prune enables full reconcile.
  if [ "$DO_BLUEPRINT" = "1" ]; then
    echo "step 'applying system blueprint'"
    cat <<'BLUEPRINT_FN'
_ump_apply_blueprint() {
  local bs="$HOME/bin/dotty-private/.claude/blueprint/bootstrap.sh"
  if [ ! -x "$bs" ]; then
    echo "  no blueprint at $bs; skipped"
    return 0
  fi
BLUEPRINT_FN
    if [ "$BLUEPRINT_PRUNE" = "1" ]; then
      echo "  bash \"\$bs\" --prune || echo '  ⚠ blueprint apply failed (continuing)'"
    else
      echo "  bash \"\$bs\" || echo '  ⚠ blueprint apply failed (continuing)'"
    fi
    echo "}"
    echo "_ump_apply_blueprint"
  fi

  if [ "$INCLUDE_MACOS" = "1" ] && [ -n "$macos_labels" ]; then
    echo "step 'applying macOS minor updates (will restart)'"
    while IFS= read -r label; do
      [ -n "$label" ] || continue
      echo "sudo softwareupdate --install --restart --label \"$label\" || true"
    done <<< "$macos_labels"
  fi

  echo
  echo "step 'cleanup'"
  echo "brew cleanup || true"
  echo "step 'done'"
} > "$remote"

if [ "$DRY" = "1" ]; then
  echo "# would run on $HOST:"
  cat "$remote"
  exit 0
fi

# Upload the script as a file (rather than piping over stdin) and execute it
# remotely. Adding ServerAliveInterval keeps the SSH session healthy through
# long brew operations. Avoiding `bash -s` over stdin makes the apply more
# resilient to transient pipe stalls — the script lives on disk on the target
# so re-runs and post-mortems are easy.
remote_path="/tmp/update-mbp-apply.$$.sh"
scp -q -o ServerAliveInterval=30 -o ServerAliveCountMax=240 "$remote" "$HOST:$remote_path"
# -t allocates a pseudo-TTY so sudo can prompt for a password when needed
# (mas upgrade, some cask upgrades, softwareupdate). The password goes
# directly from the user's keyboard to the remote sudo — not captured.
ssh -t -o ServerAliveInterval=30 -o ServerAliveCountMax=240 \
    "$HOST" "bash $remote_path; rm -f $remote_path"
